### ISSUE TITLE
upload_session query param in upload_documents_url

### ISSUE THREAD

**Issue by rubendel** [buildingSMART/documents-API#10]
Referring to the documentation at [upload_documents_url](https://github.com/buildingSMART/documents-API#33224-client-queries-upload-instructions)

It looks like the request and response are both documented in openapi spec, but the `upload_session` query parameter is not part of it. When generating either server-stub or client, in most frameworks there is no way to shoehorn it in. It would be really nice to use the generated code for these calls instead of manually coding them.

Perhaps there is a good reason for this, but why can't the `upload_session` be part of the request (json)? I understand this is kind of a private path on the CDE (CDE generating the URL and also consuming it), but still.

**Comment by GeorgDangl** [comment]
Hey @rubendel, thank you for the input!

As far as I understand it, the `upload_session` parameter in the example is part of the provided url, so it's not an actual part of the specification but something that is server generated. It could just as well be `totally_not_a_standard_parameter=any_value`, since it's really just part of the url that the client receives.

We've included it in the docs as to demo that clients might expect query parameters to be part of the urls.

**Comment by GeorgDangl** [comment]
At least I think so, would be happy to get input from @jasollien or @ykulbak😀

**Comment by ykulbak** [comment]
That's right. The `upload_session` parameter is just part of an example URL.  The client is supposed to use the `upload_documents_url`, `upload_completion` or `upload_cancellation` URLs as-is without making any assumptions on their structure.

**Comment by rubendel** [comment]
Ok clear, thank you @GeorgDangl and @ykulbak. Is it safe to say that the OpenAPI specs regarding those types of calls (the calls prefixed with `server_provided_path`) can only be used for the request/response message structure (which is definitely useful) but not for the path structure and query params?

**Comment by ykulbak** [comment]
@rubendel the openapi calls prefixed in `server_provided_path` can be used also for path structure and query params. 

I believe that the confusion here is because the *value* of some query parameters is a URL.  If you take, for example, the exchange detailed in [3.3.2.2.3. User Enters File Data in CDE UI](https://github.com/buildingSMART/documents-API#33223-user-enters-file-data-in-cde-ui) the in the URL: 

`http://localhost:8080/cde-callback-example?upload_documents_url=https%3A%2F%2Fcde.example.com%2Fupload-instructions%3Fupload_session%3Dee56b8f3-8f93-4819-976e-46a45a5a996f.` 

The query parameter `upload_documents_url` is part of the specification. Your implementation can and should rely on it.

The query parameter `upload_session` is part of the value of  the `upload_documents_url` query parameter. It's only provided in the spec as a "real-world" example of how some servers may structure the response. Your implementation can't rely on the structure of that URL. Your implementation can only assume:

1. That the value of `upload_documents_url` is a valid URL
2. The client can call it using the current user's bearer token to retrieve the upload payload

**Comment by GeorgDangl** [comment]
This seems like it’s a bit confusing, so we should talk about this in the next Meeting how to make that more clear in the documentation.

**Comment by rubendel** [comment]
Thanks again for your comments. Been working on this for the past few days and understanding it all much better now (I think). I'll describe what I did, if you could verify that would be great.

1. Removed all the `server-provided-path` paths from the documents openapi spec, then generated server stubs (so 3 methods)
2. Created a new openapi spec, which is specific for our product (it's a server product just to be clear). This spec is not at all intended to be public in any way, just a way of generating the server stubs. In this spec are all the `server-provided-path` paths copied over from the original spec. Renamed the paths. Also added query params wherever they were needed [1]. I referenced the original spec for all the schemas. Generated servers stubs for those as well.
3. Implemented all calls for the above.

[1] @ykulbak Have to say I don't think your statement about the `server_provided_path` being usable for path structure and query params is correct, not that it is a big deal btw. Any implementation I think will use different paths, and custom query params. Without adding either path/query/header/cookie parameters, how would we be able to send any information to the server? For example the `server-provided-path-document-upload-completion` definition. It has no params of any kind in the openapi spec. How would the server know which upload has actually been completed? I understand the implementation is going to be different per CDE.

Personally I still think it is a good idea to include the `server_provided_path` paths in the spec (the response definitions but also documentation on them is very useful), but perhaps the documentation could be more clear that these calls can/should be modified by adding params for example. It might be useful to perhaps split the openapi spec into 2, to make it more clear that the first spec is fixed (all input/output/paths defined and cannot be deviated from) and the second spec is to be modified by the CDE implementor (but outputs are fixed).

Just hope I am not understanding it all wrong... ;)
